name: Run Tests

on:
  push:        # Run on every push
    branches: ["**"]   # all branches
  pull_request:        # Also run on PRs
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # or your project’s Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
